name: Build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: ["metro_m0_express", "metro_m4_express"]
    
    steps:
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install deps
      run: |
        sudo apt-get install -y gettext
        pip install sh click setuptools
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: mpy-cross
      run: make -C mpy-cross -j2
    - name: build
      run: pushd tools && TRAVIS_BOARDS="${{ matrix.board }}" python3 -u build_release_files.py && popd
