name: Build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: ["metro_m0_express"]
    
    steps:
    - uses: actions/checkout@v1
    - name: mpy-cross
      run: make -C mpy-cross -j2
    - name: build
      run: pushd tools && TRAVIS_BOARDS="${{ matrix.board }}" python3 -u build_release_files.py && popd
