name: Build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: ["metro_m0_express", "metro_m4_express"]
    
    steps:
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install deps
      run: |
        sudo apt-get install -y gettext
        pip install requests sh click setuptools
        wget https://s3.amazonaws.com/adafruit-circuit-python/gcc-arm-embedded_7-2018q2-1~xenial1_amd64.deb && sudo dpkg -i gcc-arm-embedded*_amd64.deb
    - name: Versions
      run: |
        gcc --version
        arm-none-eabi-gcc --version
        python3 --version
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: mpy-cross
      run: make -C mpy-cross -j2
    - name: build
      run: pushd tools && TRAVIS_BOARDS="${{ matrix.board }}" python3 -u build_release_files.py && popd
